FROM python:3.12-slim-bullseye as base

WORKDIR /app

# use uv for dependency management
COPY ./pyproject.toml ./uv.lock* ./
RUN pip install --no-cache-dir uv \
    && uv sync --locked --no-install-project --no-dev

COPY main.py ./
COPY ./app ./app

RUN uv run python3 -m compileall /app

FROM python:3.12-slim-bullseye
COPY --from=base /app /app
WORKDIR /app
ENTRYPOINT ["/app/main.py"]
CMD ["--host", "0.0.0.0", "--port", "80"]
